# Generated by Django 4.1.3 on 2023-03-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('designation_short', models.CharField(blank=True, max_length=3, null=True)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=128, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', '--Please Select--'), ('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, max_length=10, null=True)),
                ('joining_date', models.DateField(blank=True, max_length=10, null=True)),
                ('office', models.CharField(blank=True, max_length=128, null=True)),
                ('present_address', models.TextField(blank=True, max_length=1000, null=True)),
                ('permanent_address', models.TextField(blank=True, max_length=1000, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/profile/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='user/sign/')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
